#pragma once

#define ENABLE_ANTI_ALIASING
#define ENABLE_REFRACTION
#define ENABLE_REFLECTION
#define ENABLE_GLOSSY_REFLECTION
#define ENABLE_GLOSSY_REFRACTION
#define ENABLE_MULTITHREAD
#define ENABLE_DEPTH_OF_FIELD
#define ENABLE_TEXTURE_MAPPING
#define ENABLE_MOTION_BLUR
#define ENABLE_BVH